[package]
name = "r1cs-std"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
edition = "2018"
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"

################################# Dependencies ################################

[dependencies]
algebra = { path = "../../../algebra" }
r1cs-core = { path = "../../core"}
derivative = "1"
radix_trie = "0.1"

[dev-dependencies]
rand = { version = "0.7" }
rand_xorshift = { version = "0.2" }
