[package]
name = "r1cs-crypto"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

################################# Dependencies ################################

[dependencies]
algebra = { path = "../../../algebra" }
primitives = {path = "../../../primitives"}
r1cs-core = { path = "../../core"}
r1cs-std = { path = "../std"}
proof-systems = { path = "../../../proof-systems", features = ["groth16", "gm17"], optional = true }
bench-utils = { path = "../../../bench-utils" }

digest = { version = "0.7", optional = true }
blake2 = { version = "0.7", optional = true }

rand = { version = "0.7" }
derivative = "1"
rayon = "1"

[features]
commitment = ["primitives/commitment", "prf"]
merkle_tree = ["primitives/merkle_tree"]
prf = ["digest", "blake2", "primitives/prf"]
signature = ["primitives/signature", "digest"]
vrf = ["primitives/vrf"]
nizk = ["proof-systems"]

[dev-dependencies]
criterion = "0.2"
rand_xorshift = { version = "0.2" }