[package]
name = "algebra"
version = "0.1.0"
authors = ["DanieleDiBenedetto <daniele@horizenlabs.io>"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"


################################# Dependencies ################################

[dependencies]
byteorder = { version = "1" }
rand = { version = "0.7" }
derivative = { version = "1" }

colored = { version = "1", optional = true }
rayon = { version = "1", optional = true }
clippy = { version = "*", optional = true }

[dev-dependencies]
blake2 = "0.7"
criterion = "0.2"
rand_xorshift = { version = "0.2" }

[features]
parallel = [ "rayon" ]
fft = ["rayon"]
